const characters = [
  {
    id: 1,
    src: '/img/Ami.webp',
    name: 'Ami',
    checked: false,
  },
  {
    id: 2,
    src: '/img/Baby Coco.webp',
    name: 'Baby Coco',
    checked: false,
  },
  {
    id: 3,
    src: '/img/Baby Cortex.webp',
    name: 'Baby Cortex',
    checked: false,
  },
  {
    id: 4,
    src: '/img/Baby Crash.webp',
    name: 'Baby Crash',
    checked: false,
  },
  {
    id: 5,
    src: '/img/Baby N. Tropy.webp',
    name: 'Baby N. Tropy',
    checked: false,
  },
  {
    id: 6,
    src: '/img/Baby T.webp',
    name: 'Baby T',
    checked: false,
  },
  {
    id: 7,
    src: '/img/Big Norm.webp',
    name: 'Big Norm',
    checked: false,
  },
  {
    id: 8,
    src: '/img/Chick.webp',
    name: 'Chick',
    checked: false,
  },
  {
    id: 9,
    src: '/img/Coco Bandicoot.webp',
    name: 'Coco Bandicoot',
    checked: false,
  },
  {
    id: 10,
    src: '/img/Crash Bandicoot.webp',
    name: 'Crash Bandicoot',
    checked: false,
  },
  {
    id: 11,
    src: '/img/Crunch Bandicoot.webp',
    name: 'Crunch Bandicoot',
    checked: false,
  },
  {
    id: 12,
    src: '/img/Dingodile.webp',
    name: 'Dingodile',
    checked: false,
  },
  {
    id: 13,
    src: '/img/Dr. N. Brio.webp',
    name: 'Dr. N. Brio',
    checked: false,
  },
  {
    id: 14,
    src: '/img/Dr. N. Gin.webp',
    name: 'Dr. N. Gin',
    checked: false,
  },
  {
    id: 15,
    src: '/img/Dr. N. Trophy.webp',
    name: 'Dr. N. Trophy',
    checked: false,
  },
  {
    id: 16,
    src: '/img/Dr. Neo Cortex.webp',
    name: 'Dr. Neo Cortex',
    checked: false,
  },
  {
    id: 17,
    src: '/img/Ebenezer Von Clutch.webp',
    name: 'Ebenezer Von Clutch',
    checked: false,
  },
  {
    id: 18,
    src: '/img/Emperor Velo XXVII.webp',
    name: 'Emperor Velo XXVII',
    checked: false,
  },
  {
    id: 19,
    src: '/img/Fake Crash.webp',
    name: 'Fake Crash',
    checked: false,
  },
  {
    id: 20,
    src: '/img/Geary.webp',
    name: 'Geary',
    checked: false,
  },
  {
    id: 21,
    src: '/img/Gnasty.webp',
    name: 'Gnasty',
    checked: false,
  },
  {
    id: 22,
    src: '/img/Hasty.webp',
    name: 'Hasty',
    checked: false,
  },
  {
    id: 23,
    src: '/img/Hunter.webp',
    name: 'Hunter',
    checked: false,
  },
  {
    id: 24,
    src: '/img/Iron Checkpoint Crate.webp',
    name: 'Iron Checkpoint Crate',
    checked: false,
  },
  {
    id: 25,
    src: '/img/Isabella.webp',
    name: 'Isabella',
    checked: false,
  },
  {
    id: 26,
    src: '/img/King Chicken.webp',
    name: 'King Chicken',
    checked: false,
  },
  {
    id: 27,
    src: '/img/Koala Kong.webp',
    name: 'Koala Kong',
    checked: false,
  },
  {
    id: 28,
    src: '/img/Komodo Joe.webp',
    name: 'Komodo Joe',
    checked: false,
  },
  {
    id: 29,
    src: '/img/Komodo Moe.webp',
    name: 'Komodo Moe',
    checked: false,
  },
  {
    id: 30,
    src: '/img/Krunk.webp',
    name: 'Krunk',
    checked: false,
  },
  {
    id: 31,
    src: '/img/Lab Assistant.webp',
    name: 'Lab Assistant',
    checked: false,
  },
  {
    id: 32,
    src: '/img/Liz.webp',
    name: 'Liz',
    checked: false,
  },
  {
    id: 33,
    src: '/img/Megamix.webp',
    name: 'Megamix',
    checked: false,
  },
  {
    id: 34,
    src: '/img/Megumi.webp',
    name: 'Megumi',
    checked: false,
  },
  {
    id: 35,
    src: '/img/N. Trance.webp',
    name: 'N. Trance',
    checked: false,
  },
  {
    id: 36,
    src: '/img/Nash.webp',
    name: 'Nash',
    checked: false,
  },
  {
    id: 37,
    src: '/img/Nina Cortex.webp',
    name: 'Nina Cortex',
    checked: false,
  },
  {
    id: 38,
    src: '/img/Nitros Oxide.webp',
    name: 'Nitros Oxide',
    checked: false,
  },
  {
    id: 39,
    src: '/img/Papu Papu.webp',
    name: 'Papu Papu',
    checked: false,
  },
  {
    id: 40,
    src: "/img/Pasadena O'Possum.webp",
    name: "Pasadena O'Possum",
    checked: false,
  },
  {
    id: 41,
    src: '/img/Penta Penguin.webp',
    name: 'Penta Penguin',
    checked: false,
  },
  {
    id: 42,
    src: '/img/Pinstripe.webp',
    name: 'Pinstripe',
    checked: false,
  },
  {
    id: 43,
    src: '/img/Polar.webp',
    name: 'Polar',
    checked: false,
  },
  {
    id: 44,
    src: '/img/Pura.webp',
    name: 'Pura',
    checked: false,
  },
  {
    id: 45,
    src: '/img/Real Velo.webp',
    name: 'Real Velo',
    checked: false,
  },
  {
    id: 46,
    src: '/img/Rilla Roo.webp',
    name: 'Rilla Roo',
    checked: false,
  },
  {
    id: 47,
    src: '/img/Ripper Roo.webp',
    name: 'Ripper Roo',
    checked: false,
  },
  {
    id: 48,
    src: '/img/Small Norm.webp',
    name: 'Small Norm',
    checked: false,
  },
  {
    id: 49,
    src: '/img/Spyro.webp',
    name: 'Spyro',
    checked: false,
  },
  {
    id: 50,
    src: '/img/Stew.webp',
    name: 'Stew',
    checked: false,
  },
  {
    id: 51,
    src: '/img/Tawna.webp',
    name: 'Tawna',
    checked: false,
  },
  {
    id: 52,
    src: '/img/Tiny Tiger.webp',
    name: 'Tiny Tiger',
    checked: false,
  },
  {
    id: 53,
    src: '/img/Yaya Panda.webp',
    name: 'Yaya Panda',
    checked: false,
  },
  {
    id: 54,
    src: '/img/Zam.webp',
    name: 'Zam',
    checked: false,
  },
  {
    id: 55,
    src: '/img/Zem.webp',
    name: 'Zem',
    checked: false,
  },
];

export default characters;
